# Generated by Django 5.2 on 2026-01-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_profile_is_verified_profile_otp_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='scam_label',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='scam_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='job_pdfs/'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
