# Generated by Django 6.0.2 on 2026-03-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_jobpost_job_type_jobpost_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
