# Generated by Django 6.0.2 on 2026-03-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_recruiterprofile_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('HR', 'HR'), ('Product', 'Product'), ('Data Science', 'Data Science'), ('Analytics', 'Analytics'), ('Design', 'Design'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('General', 'General / Other')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_size',
            field=models.CharField(choices=[('Startup', 'Startup'), ('MNC', 'MNC'), ('Fortune 500', 'Fortune 500'), ('SME', 'SME / Mid-size')], default='Startup', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Fresher', 'Fresher'), ('Entry', 'Entry Level'), ('Mid', 'Mid Level'), ('Senior', 'Senior')], default='Mid', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Onsite', 'Onsite')], default='Onsite', max_length=20),
        ),
    ]
